version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python ./django_basic_app/manage.py runserver 0.0.0.0:8800
    volumes:
      - .:/code
    ports:
      - "8800:8800"
    depends_on:
      - db
